<?php

/**
 * @file
 * Contains krocodile_manual.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function krocodile_manual_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the krocodile_manual module.
    case 'help.page.krocodile_manual':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function krocodile_manual_theme() {
  $theme = [];
  $theme['manual_kpi'] = [
    'render element' => 'elements',
    'file' => 'manual_kpi.page.inc',
    'template' => 'manual_kpi',
  ];
  $theme['manual_kpi_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'manual_kpi.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function krocodile_manual_theme_suggestions_manual_kpi(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#manual_kpi'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'manual_kpi__' . $sanitized_view_mode;
  $suggestions[] = 'manual_kpi__' . $entity->bundle();
  $suggestions[] = 'manual_kpi__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'manual_kpi__' . $entity->id();
  $suggestions[] = 'manual_kpi__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
